services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    restart: always
    environment:
      SA_PASSWORD: "TLG2023!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - tlg-data:/var/opt/mssql/tlg-data

  tlg:
    build: .
    ports:
      - "5005:80"
    depends_on:
      - sqlserver

volumes:
  tlg-data:
