version: '3'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    restart: always
    environment:
      SA_PASSWORD: "TLG2023!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - tlg-data:/var/opt/mssql/tlg-data

  tlgapi:
    build: tlg-api
    ports:
      - "5005:80"
    depends_on:
      - sqlserver
      
  react-ui:
    build:
      context: ./tlg-interface
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: react-ui
    stdin_open: true
    volumes:
       - ./my-app:/usr/src/app/tlg-interface
       - /usr/src/app/tlg-interface/node_modules
    depends_on:
      - tlgapi

volumes:
  tlg-data:
